services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hoppscotch
      POSTGRES_USER: ${POSTGRES_USER:-hoppscotch}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strong_password}
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoppscotch"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: hoppscotch/hoppscotch-backend
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-hoppscotch}:${POSTGRES_PASSWORD:-strong_password}@postgres:5432/hoppscotch-db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "3170:3170"

  frontend:
    image: hoppscotch/hoppscotch-frontend
    env_file: .env
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3000:3000"

  admin:
    image: hoppscotch/hoppscotch-admin
    env_file: .env
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "3100:3100"

volumes:
  postgres-data:

networks:
  default:
    driver: bridge